function Stats=CompileStatsDotMatFiles(varargin)

% This code compiles data from the stats.mat generated by Run_OFBATCH, and save them into a Stats vector.
% varargin should be a cell array with the absolute path of the stats.mat files to be loaded (similar to plotMySims).
% Written by Antoine - Copyright Principle Power inc. 2016


%% Select variables to be plotted from the stats.mat files
list=varargin{1};
load(char(list(1)));
Fields=fieldnames(OutS);
[iChoice, isOK] = listdlg('PromptString','Select results to plot', 'Name', 'Variables available', 'ListString',Fields );
if ~isOK
    error('User Cancelled')
end
Stats=zeros(length(list),length(iChoice));

%% Select type of statistics (mean, min, max, etc...)
FieldsStats=fieldnames(OutS.(char(Fields{2})));   %%assuming time is the first variable
[oChoice, osOK] = listdlg('PromptString','What statistics would you like to plot - ONLY one choice now', 'Name', 'Variables available', 'ListString',FieldsStats );
if ~osOK
    error('User Cancelled')
end

%% Compile the data in a Stats array
for j=1:length(iChoice)
    for i=1:length(list)
        load(char(list(i)));
        Stats(i,j)=OutS.(char(Fields(iChoice(j)))).(char(FieldsStats(oChoice)));
    end 
end
end