function[number] = importfile(fileToRead1,HEADERLINES,COLtoOutput)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 26-Aug-2016 12:54:17
DELIMITER = ',';
%HEADERLINES = 14;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
number = newData1.data(:,COLtoOutput);

